### ISSUE TITLE
Execution fails for empty CD drives

### ISSUE THREAD

**Issue by m-beno** [milkey-mouse/backup-vm#11]
If there is a cd drive with no .iso mounted, the execution of the script fails. 

```Traceback (most recent call last):
  File "/usr/bin/backup-vm", line 11, in <module>
    load_entry_point('backup-vm==0.1.dev17+gce32c59.d20171207', 'console_scripts', 'backup-vm')()
  File "/usr/lib/python3.6/site-packages/backup_vm-0.1.dev17+gce32c59.d20171207-py3.6.egg/backup_vm/backup.py", line 28, in main
    all_disks = set(parse.Disk.get_disks(dom))
  File "/usr/lib/python3.6/site-packages/backup_vm-0.1.dev17+gce32c59.d20171207-py3.6.egg/backup_vm/parse.py", line 187, in get_disks
    yield from {d for d in map(cls, tree.findall("devices/disk")) if d.type is not None}
  File "/usr/lib/python3.6/site-packages/backup_vm-0.1.dev17+gce32c59.d20171207-py3.6.egg/backup_vm/parse.py", line 187, in <setcomp>
    yield from {d for d in map(cls, tree.findall("devices/disk")) if d.type is not None}
  File "/usr/lib/python3.6/site-packages/backup_vm-0.1.dev17+gce32c59.d20171207-py3.6.egg/backup_vm/parse.py", line 163, in __init__
    if len(xml.find("source").attrib.items()) >= 1:
AttributeError: 'NoneType' object has no attribute 'attrib'
```

The issue is that the following line: https://github.com/milkey-mouse/backup-vm/blob/ce32c5917996c58e8dd43a28ef695f075532acd9/backup_vm/parse.py#L162

is looking for attributes in the "source" entry in the XML, which does not exist in the cd-rom <device>  block when there is no .iso file loaded.

**Comment by milkey-mouse** [comment]
see #12

**Comment by icebal** [comment]
i'm still facing this issue with a fresh git pull and the fix in #12  is included. 
this is a fresh install from 12 minutes ago, with a new and clean borg repo init'd.

Traceback (most recent call last):
  File "/usr/bin/backup-vm", line 11, in <module>
    load_entry_point('backup-vm==0.1.dev18+g0de28ef', 'console_scripts', 'backup-vm')()
  File "/usr/lib/python3.6/site-packages/backup_vm-0.1.dev18+g0de28ef-py3.6.egg/backup_vm/backup.py", line 28, in main
    all_disks = set(parse.Disk.get_disks(dom))
  File "/usr/lib/python3.6/site-packages/backup_vm-0.1.dev18+g0de28ef-py3.6.egg/backup_vm/parse.py", line 186, in get_disks
    yield from {d for d in map(cls, tree.findall("devices/disk")) if d.type is not None}
  File "/usr/lib/python3.6/site-packages/backup_vm-0.1.dev18+g0de28ef-py3.6.egg/backup_vm/parse.py", line 186, in <setcomp>
    yield from {d for d in map(cls, tree.findall("devices/disk")) if d.type is not None}
  File "/usr/lib/python3.6/site-packages/backup_vm-0.1.dev18+g0de28ef-py3.6.egg/backup_vm/parse.py", line 158, in __init__
    self.format = xml.find("driver").attrib["type"]
AttributeError: 'NoneType' object has no attribute 'attrib'

**Comment by m-beno** [comment]
Similar issue, but not the same. Your script fails a few lines earlier. It almost seems that you have no <driver> block in the XML that defines the VM. For reference, this is how it usually looks:

```
    <disk type='block' device='disk'>
      <driver name='qemu' type='raw' cache='none' io='native'/>
      <source dev='/dev/lvmdev/ubuntu'/>
      <target dev='vda' bus='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x09' function='0x0'/>
    </disk>
```

Mind sharing this part of your XML file? I've never seen one without the <driver> block before. If it's indeed missing it might be a good idea to implement a similar check as for the optical drives.

**Comment by icebal** [comment]
here ya go, fresh from the source :D 
 https://ptpb.pw/G-XV

**Comment by icebal** [comment]
the relevent part looks to be below. this is in iso mode, not host device, maybe thats why?
 </disk>
    <disk type='file' device='cdrom'>
      <backingStore/>
      <target dev='sda' bus='sata'/>
      <readonly/>
      <alias name='sata0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>

**Comment by m-beno** [comment]
I guess you can implement a similar check to the relevant part of the code. Something like this: 
```
        if xml.find("driver") is not None:
            self.format = xml.find("driver").attrib["type"]
        else:
            self.format = None
```
Not sure if it breaks anything else, so I won't do a PR yet. 

I can't even delete the `<driver>` for testing purposes. Libvirt automatically adds it to the XML again as soon as I close it. So this is untested. Again, it's weird that it's missing in your xml.

**Comment by icebal** [comment]
changing that and remaking got me to atleast backup progress: 0%, it currently looks to be backing up!
and for more info on that VM, it was build using virt-manager and libvirt.

**Comment by icebal** [comment]
backup worked successfully, looks like that fix works (for me anyways)

**Comment by milkey-mouse** [comment]
Because `get_disks()` automatically filters out disks without a `type` entry, the empty CD drive will be filtered out; in other words, it only matters that the Disk object can be created without crashing and not that it actually has the data needed to back up the disk:

https://github.com/milkey-mouse/backup-vm/blob/e100fc38d92b90d8216865f6b2d19fb953599e0e/backup_vm/parse.py#L176-187

**Comment by milkey-mouse** [comment]
If there is really a disk with an unknown `<driver>` that is valid (and needs to be backed up), that could be an issue:

https://github.com/milkey-mouse/backup-vm/blob/e100fc38d92b90d8216865f6b2d19fb953599e0e/backup_vm/builder.py#L36

I'll be sure to handle it although I haven't personally encountered that edge case.
