### ISSUE TITLE
Python 3.5 required?

### ISSUE THREAD

**Issue by magma1447** [milkey-mouse/backup-vm#22]
The README says that Python >=3.4 is required, however, with 3.4 I am getting this error:
`
 File "setup.py", line 22
    lines = [*self.format_readme(f)]
                        ^
SyntaxError: can use starred expression only as assignment target
`

I am by no means an expert with Python, quite the opposite, and may therefore be wrong. But my Google skills says that this syntax requires Python 3.5.

**Comment by milkey-mouse** [comment]
You're right. For this specific issue there's an easy fix that makes it Python 3.4 compatible, but I'll update the README to only advertise compatibility with 3.5 and later anyway because Python 3.4 is [end-of-lifed](https://www.python.org/downloads/release/python-3410/).

**Comment by milkey-mouse** [comment]
FWIW that line is in `build_usage`, which shouldn't run during normal installation & usage. I guess Python must be parsing the whole file first anyway.
