### ISSUE TITLE
Integration into existing backup process

### ISSUE THREAD

**Issue by rugk** [milkey-mouse/backup-vm#4]
How is it intended to be integrated into an existing backup process? E.g. in [my script](https://github.com/rugk/borg-cron-helper) a usual backup is done. If I wanted to include VM images inside of it, I would need to dump these and then backup everything.

But this script automatically executes the backup, so is it designed to have an extra repo just for VM images? (In the usual use case, i think, I want to backup both, usual data and VMs) Or may I just backup the VMs into the same repo, but with a different archive name?

**Comment by milkey-mouse** [comment]
It is designed to have a separate repo, or at least separate backups in the same repo. The file layout of the VM backup has each disk in the root repository (so you can just do `borg extract sda.raw`, etc.) which will make it easier to restore them after. It is totally possible to have your normal backups and your VMs share the same repository. For example, on my machine, I have a cron job that makes a `rootfs-{date}` and a `vm-{date}` in the same borg repo, which gives you the benefit of deduplication (not that it would help very much unless your host shares lots of files with your VM for some reason).

**Comment by rugk** [comment]
Okay, that sounds good.
