### ISSUE TITLE
How to pass additional commands to script?

### ISSUE THREAD

**Issue by rugk** [milkey-mouse/backup-vm#5]
AFAIK as you call borg directly in the script, it may be hard to pass additional commands to it. E.g. you cannot configure `--compression`, `--chunker-params`, etc.

Can't we use this in a more flexible way? Or is there no reason to configure it in such a way? (if so… why?)

**Comment by milkey-mouse** [comment]
You can pass arguments directly to borg, with the `--borg-args` command. See the second [usage example](https://github.com/milkey-mouse/backup-vm#backup).
